/* Append-only v52 Guess the Word rows: [term, seven pipe-separated forbidden clues, source]. */
const v52WordRows = [
  ["TAWADU‘","humility|lower|pride|modest|servant|arrogance|gentle","Qur’an 25:63"],
  ["HIKMAH","wisdom|judgment|knowledge|apply|insight|appropriate|sound","Qur’an 2:269"],
  ["BASIRAH","insight|clear|evidence|perception|understanding|call|discernment","Qur’an 12:108"],
  ["INABAH","return|Allah|turn|repent|heart|devotion|back","Qur’an 39:54"],
  ["KHASHYAH","reverent|fear|knowledge|Allah|awe|scholars|humility","Qur’an 35:28"],
  ["YAQIN","certainty|doubt|conviction|sure|truth|faith|confidence","Qur’an 15:99"],
  ["ISTIQAMAH","steadfast|upright|remain|consistent|path|firm|straight","Qur’an 41:30"],
  ["ITHAR","prefer|others|need|self|generosity|share|priority","Qur’an 59:9"],
  ["RIFQ","gentleness|soft|kindness|harsh|grace|matter|beautifies","Sahih Muslim 2594"],
  ["SAKHA’","generosity|openhanded|giving|wealth|liberal|share|stingy","Sahih al-Bukhari 3554"],
  ["KARAM","nobility|generous|honor|guest|character|giving|dignity","Sahih al-Bukhari 6018"],
  ["WAFA’","fulfill|promise|covenant|loyalty|commitment|keep|word","Qur’an 16:91"],
  ["SAMAHAH","easygoing|lenient|trade|gracious|buyer|seller|mercy","Sahih al-Bukhari 2076"],
  ["SHAJA‘AH","courage|bravery|fear|stand|danger|truth|strength","Sahih Muslim 2664"],
  ["TAWBAH NASUH","sincere|repentance|return|sin|resolve|pure|reform","Qur’an 66:8"],
  ["SAKINAH","tranquility|descend|hearts|calm|believers|peace|assurance","Qur’an 48:4"],
  ["TUMA’NINAH","settled|heart|tranquility|remembrance|rest|calm|assured","Qur’an 13:28"],
  ["AL-HUBB FILLAH","love|Allah|brotherhood|sake|bond|faith|friendship","Sahih Muslim 2567"],
  ["AL-BUGHD FILLAH","dislike|Allah|sake|faith|wrong|principle|enmity","Qur’an 58:22"],
  ["SITR","conceal|fault|privacy|cover|Muslim|expose|Allah","Sahih Muslim 2699"],
  ["HUSN AL-KHULUQ","good|character|manners|conduct|behavior|best|ethics","Sahih al-Bukhari 6035"],
  ["‘AFIYAH","wellbeing|safety|health|protection|ease|ask|harm","Qur’an 2:201"],
  ["FARAJ","relief|hardship|opening|distress|ease|after|trial","Qur’an 94:5–6"],
  ["IBTILA’","test|trial|affliction|wealth|fear|loss|patience","Qur’an 2:155"],
  ["THABAT","firmness|steady|establish|believers|word|world|afterlife","Qur’an 14:27"],
  ["AYAH","verse|sign|Qur’an|chapter|revelation|number|recite","Qur’an 2:106"],
  ["SURAH","chapter|Qur’an|verses|name|revelation|opening|section","Qur’an 24:1"],
  ["JUZ’","thirtieth|portion|Qur’an|division|reading|part|completion","Qur’an 73:20"],
  ["HIZB","sixtieth|portion|Qur’an|division|recitation|part|marker","Qur’an 73:20"],
  ["MUSHAF","written|Qur’an|pages|codex|copy|script|binding","Qur’an 56:77–79"],
  ["TILAWAH","recitation|follow|Qur’an|read|verses|voice|worship","Qur’an 2:121"],
  ["TARTIL","measured|recitation|Qur’an|slow|clear|rhythm|careful","Qur’an 73:4"],
  ["TAJWID","recitation|pronunciation|letters|rules|Qur’an|articulation|correct","Qur’an 73:4"],
  ["QIRA’AT","canonical|readings|Qur’an|recitation|transmission|variants|chains","Sahih al-Bukhari 4992"],
  ["TAFSIR","explanation|Qur’an|meaning|interpretation|verses|context|commentary","Qur’an 16:44"],
  ["ASBAB AL-NUZUL","occasions|revelation|context|why|verse|event|background","Qur’an 58:1"],
  ["MUHKAM","clear|verses|foundation|book|decisive|meaning|unambiguous","Qur’an 3:7"],
  ["MUTASHABIH","ambiguous|verses|resemblance|interpretation|hearts|clear|trial","Qur’an 3:7"],
  ["NASIKH","abrogating|ruling|later|verse|replaces|legal|revelation","Qur’an 2:106"],
  ["MANSUKH","abrogated|ruling|earlier|replaced|verse|legal|revelation","Qur’an 2:106"],
  ["MAKKI","Mecca|before|Hijrah|revelation|surah|period|classification","Qur’an 6:92"],
  ["MADANI","Medina|after|Hijrah|revelation|surah|period|classification","Qur’an 2:151"],
  ["MUQATTA‘AT","disconnected|letters|openings|surahs|Alif|Lam|Mim","Qur’an 2:1"],
  ["SAJDAT AL-TILAWAH","prostration|recitation|verse|Qur’an|hear|reader|bow","Sahih al-Bukhari 1077"],
  ["WAQF WA IBTIDA’","stop|start|recitation|meaning|pause|Qur’an|breath","Qur’an 73:4"],
  ["HIFZ","memorization|Qur’an|preserve|heart|recall|learn|retain","Qur’an 54:17"],
  ["HAFIZ","memorizer|Qur’an|entire|heart|recite|preserve|person","Sahih al-Bukhari 5027"],
  ["KHATM AL-QUR’AN","complete|recitation|whole|finish|Qur’an|cycle|reading","Qur’an 73:20"],
  ["QARI’","reciter|Qur’an|voice|reader|tajwid|person|melody","Sahih al-Bukhari 5027"],
  ["AHRUF","seven|modes|Qur’an|revealed|recitation|ease|dialects","Sahih al-Bukhari 4992"],
  ["ISNAD","chain|narrators|transmission|report|from|authority|hadith","Ibn al-Salah, Muqaddimah; see Sahih Muslim, Introduction"],
  ["MATN","text|wording|report|hadith|chain|content|statement","Ibn al-Salah, Muqaddimah; see Sahih Muslim, Introduction"],
  ["RAWI","narrator|transmitter|person|report|chain|hadith|relate","Ibn al-Salah, Muqaddimah; see Sahih Muslim, Introduction"],
  ["MUHADDITH","hadith|scholar|narrations|chains|expert|transmitters|critic","Ibn al-Salah, Muqaddimah; see Sahih Muslim, Introduction"],
  ["SAHIH HADITH","authentic|sound|chain|narrators|reliable|continuous|defect","Ibn al-Salah, Muqaddimah; see Sahih al-Bukhari"],
  ["HASAN HADITH","good|acceptable|grading|report|authentic|narrator|memory","Ibn al-Salah, Muqaddimah; see Jami‘ al-Tirmidhi"],
  ["DA‘IF HADITH","weak|grading|chain|narrator|defect|report|authenticity","Ibn al-Salah, Muqaddimah; see Sunan Abi Dawud"],
  ["MUTAWATIR","mass-transmitted|numerous|chains|report|collusion|certainty|generation","Ibn al-Salah, Muqaddimah; see Sahih Muslim"],
  ["AHAD HADITH","limited|chains|report|mass|transmission|single|category","Ibn al-Salah, Muqaddimah; see Sahih al-Bukhari"],
  ["HADITH QUDSI","divine|report|Allah|Prophet|Qur’an|meaning|narrates","Sahih Muslim 2577"],
  ["MARFU‘","attributed|Prophet|report|companion|chain|statement|action","Ibn al-Salah, Muqaddimah; see Sahih al-Bukhari"],
  ["MAWQUF","companion|attributed|report|Prophet|statement|stopped|chain","Ibn al-Salah, Muqaddimah; see Sahih al-Bukhari"],
  ["MAQTU‘","successor|attributed|report|companion|statement|chain|stopped","Ibn al-Salah, Muqaddimah; see Sahih Muslim"],
  ["MURSAL","successor|omits|companion|chain|Prophet|report|disconnected","Ibn al-Salah, Muqaddimah; see Sunan Abi Dawud"],
  ["MUSNAD","connected|chain|collection|attributed|Prophet|report|narrators","Ibn al-Salah, Muqaddimah; see Musnad Ahmad"],
  ["JAMI‘","collection|hadith|topics|belief|law|manners|history","Ibn al-Salah, Muqaddimah; see Sahih al-Bukhari"],
  ["SUNAN COLLECTION","hadith|legal|chapters|rulings|collection|reports|fiqh","Ibn al-Salah, Muqaddimah; see Sunan Abi Dawud"],
  ["MUSANNAF","arranged|legal|chapters|reports|companions|successors|collection","Ibn al-Salah, Muqaddimah; see Sahih al-Bukhari"],
  ["SAHIHAYN","two|authentic|Bukhari|Muslim|collections|books|hadith","Sahih al-Bukhari; Sahih Muslim"],
  ["JARH WA TA‘DIL","narrator|criticism|praise|reliability|biography|hadith|evaluation","Ibn al-Salah, Muqaddimah; see Sahih Muslim, Introduction"],
  ["TAKHRIJ","locate|hadith|sources|chains|grading|reference|trace","Ibn al-Salah, Muqaddimah; see Sahih Muslim, Introduction"],
  ["RIWAYAH","transmission|narration|report|chain|hadith|relate|wording","Ibn al-Salah, Muqaddimah; see Sahih al-Bukhari"],
  ["DIRAYAH","analysis|understanding|hadith|method|criticism|meaning|knowledge","Ibn al-Salah, Muqaddimah; see Sahih Muslim, Introduction"],
  ["IJAZAH","authorization|teacher|student|transmit|chain|permission|text","Ibn al-Salah, Muqaddimah; see Sahih al-Bukhari"],
  ["MUDALLAS","concealed|chain|omission|narrator|ambiguous|transmission|hadith","Ibn al-Salah, Muqaddimah; see Sahih Muslim, Introduction"],
  ["TAHARAH","purity|clean|worship|wudu|ghusl|prayer|state","Qur’an 5:6"],
  ["NAJASAH","ritual|impurity|remove|clean|prayer|substance|purification","Sahih al-Bukhari 220"],
  ["GHUSL","full|bath|ritual|washing|major|purity|body","Qur’an 5:6"],
  ["ISTINJA’","cleaning|toilet|water|private|relief|purity|remove","Sahih al-Bukhari 150"],
  ["MASAH","wipe|wet|head|wudu|hands|water|purification","Qur’an 5:6"],
  ["KHUFFAYN","leather|socks|wipe|feet|travel|purification|footwear","Sahih Muslim 274"],
  ["ADHAN","call|prayer|muadhdhin|Allahu Akbar|time|mosque|voice","Sahih al-Bukhari 604"],
  ["IQAMAH","second|call|prayer|stand|begin|congregation|lines","Sahih al-Bukhari 605"],
  ["JAMA‘AH","congregation|group|prayer|together|imam|rows|mosque","Sahih al-Bukhari 645"],
  ["JUMU‘AH","Friday|prayer|sermon|congregation|noon|weekly|mosque","Qur’an 62:9"],
  ["KHUTBAH","sermon|Friday|speaker|pulpit|listen|address|prayer","Qur’an 62:9–10"],
  ["QUNUT","supplication|standing|prayer|witr|devotion|obedience|dua","Sahih al-Bukhari 1001"],
  ["TAHIYYAT AL-MASJID","greeting|mosque|two|rak‘ahs|sit|enter|prayer","Sahih al-Bukhari 444"],
  ["SUJUD AL-SAHW","forgetfulness|prostration|mistake|prayer|extra|before|after","Sahih al-Bukhari 1224"],
  ["SAJDAT AL-SHUKR","gratitude|prostration|good|news|blessing|thank|Allah","Sunan Abi Dawud 2774"],
  ["QASR","shorten|travel|four|two|rak‘ahs|prayer|journey","Qur’an 4:101"],
  ["JAM‘ AL-SALAH","combine|prayers|travel|noon|afternoon|sunset|night","Sahih Muslim 705"],
  ["MUSAFIR","traveler|journey|prayer|fast|distance|concession|away","Qur’an 2:184–185"],
  ["SUHUR","pre-dawn|meal|fast|before|Fajr|eat|blessing","Sahih al-Bukhari 1923"],
  ["IFTAR","break|fast|sunset|dates|eat|Maghrib|evening","Sahih al-Bukhari 1957"],
  ["IMSAK","abstain|fast|dawn|food|drink|begin|stop","Qur’an 2:187"],
  ["LAYLAT AL-QADR","night|decree|thousand|months|Ramadan|angels|worship","Qur’an 97:1–5"],
  ["ZAKAT AL-FITR","charity|Ramadan|food|Eid|person|poor|sunset","Sahih al-Bukhari 1503"],
  ["NISAB","minimum|threshold|zakah|wealth|amount|liable|savings","Sahih al-Bukhari 1459"],
  ["HAWL","lunar|year|zakah|wealth|possession|cycle|elapsed","Sunan Abi Dawud 1573"],
  ["‘USHR","tenth|harvest|rain|crops|zakah|irrigation|produce","Sahih al-Bukhari 1483"],
  ["TAWAF","circle|Ka‘bah|seven|Hajj|‘Umrah|walk|House","Qur’an 22:29"],
  ["SA‘I","Safa|Marwah|seven|walk|Hajj|‘Umrah|between","Qur’an 2:158"],
  ["WUQUF BI ‘ARAFAH","stand|plain|ninth|Hajj|pilgrims|day|essential","Sahih Muslim 1218"],
  ["MUZDALIFAH","night|Hajj|‘Arafah|Mina|gather|pilgrims|Mash‘ar","Qur’an 2:198"],
  ["MINA","tents|Hajj|days|pilgrims|Jamarat|stay|sacrifice","Qur’an 2:203"],
  ["JAMARAT","pillars|stones|throw|Hajj|Mina|three|ritual","Sahih al-Bukhari 1751"],
  ["HADY","sacrificial|animal|Hajj|offering|sanctuary|pilgrim|slaughter","Qur’an 2:196"],
  ["RAMY","throwing|pebbles|Jamarat|Hajj|Mina|seven|ritual","Sahih al-Bukhari 1751"],
  ["TAHALLUL","exit|ihram|hair|restrictions|Hajj|‘Umrah|completion","Qur’an 2:196"],
  ["MIQAT","boundary|ihram|pilgrim|Hajj|‘Umrah|location|enter","Sahih al-Bukhari 1524"],
  ["MAHRAM","unmarriageable|relative|travel|woman|kinship|permanent|guardian","Sahih al-Bukhari 1862"],
  ["KHALWAH","seclusion|unrelated|man|woman|private|alone|third","Sahih al-Bukhari 5233"],
  ["SAWM","fast|dawn|sunset|food|drink|Ramadan|abstain","Qur’an 2:183"],
  ["‘AQIQAH","newborn|sacrifice|seventh|day|hair|child|animal","Sahih al-Bukhari 5472"],
  ["UDHIYAH","sacrifice|Eid|animal|Adha|slaughter|worship|meat","Qur’an 22:36"],
  ["DHABH","slaughter|animal|blade|halal|blood|name|food","Sahih Muslim 1955"],
  ["TASMIYAH","Bismillah|name|Allah|begin|slaughter|eat|mention","Qur’an 6:118"],
  ["EID AL-FITR","festival|Ramadan|fast|morning|prayer|celebration|first","Sahih al-Bukhari 952"],
  ["EID AL-ADHA","festival|sacrifice|Hajj|Dhul-Hijjah|prayer|animal|tenth","Sahih al-Bukhari 955"],
  ["TAKBIRAT AL-IHRAM","opening|Allahu Akbar|prayer|begin|hands|sacred|entry","Sahih Muslim 498"],
  ["TASHAHHUD","sitting|prayer|testimony|greetings|Prophet|finger|final","Sahih al-Bukhari 831"],
  ["TASLIM","ending|prayer|peace|right|left|salam|exit","Sahih Muslim 582"],
  ["SUTRAH","barrier|prayer|front|pass|object|screen|worshipper","Sahih al-Bukhari 509"],
  ["SAFF","row|prayer|straight|congregation|shoulder|line|gap","Sahih al-Bukhari 723"],
  ["NIKAH","marriage|contract|spouse|witnesses|union|legal|consent","Qur’an 4:3"],
  ["WALIMAH","wedding|feast|marriage|meal|invite|celebration|guests","Sahih al-Bukhari 5155"],
  ["KHUL‘","wife|divorce|return|mahr|separation|request|marriage","Sahih al-Bukhari 5273"],
  ["TALAQ RAJ‘I","revocable|divorce|return|waiting|period|husband|marriage","Qur’an 2:228–229"],
  ["‘IDDAH","waiting|period|divorce|widow|marriage|months|pregnancy","Qur’an 2:228; 2:234"],
  ["NAFAQAH","maintenance|spending|family|food|housing|dependents|means","Qur’an 65:7"],
  ["HADANAH","custody|child|care|parent|welfare|upbringing|separation","Qur’an 2:233"],
  ["RADA‘AH","breastfeeding|milk|infant|two|years|mother|kinship","Qur’an 2:233"],
  ["WASIYYAH","bequest|will|death|estate|third|heirs|instruction","Qur’an 2:180"],
  ["MIRATH","inheritance|estate|heirs|shares|death|family|wealth","Qur’an 4:7"],
  ["FARA’ID","fixed|shares|inheritance|heirs|Qur’an|estate|calculation","Qur’an 4:11–12"],
  ["BAY‘","sale|trade|buyer|seller|exchange|contract|price","Qur’an 2:275"],
  ["IJARAH","lease|hire|rent|service|wage|benefit|contract","Qur’an 28:26–27"],
  ["MUDARABAH","capital|manager|profit|investment|partnership|loss|trade","Qur’an 2:198"],
  ["MUSHARAKAH","partnership|capital|shared|profit|loss|business|owners","Qur’an 38:24"],
  ["MURABAHAH","cost|markup|sale|disclosure|price|finance|asset","Qur’an 2:275"],
  ["SALAM CONTRACT","advance|payment|future|delivery|goods|specified|sale","Sahih al-Bukhari 2240"],
  ["ISTISNA‘","manufacture|order|build|contract|specifications|maker|price","Sahih al-Bukhari 2092"],
  ["QARD HASAN","benevolent|loan|repay|principal|help|interest|borrower","Qur’an 2:245"],
  ["RAHN","collateral|pledge|debt|security|possession|loan|property","Qur’an 2:283"],
  ["KAFALAH","guarantee|responsibility|debt|person|undertake|surety|obligation","Qur’an 12:72"],
  ["HAWALAH","transfer|debt|creditor|debtor|payment|obligation|third","Sahih al-Bukhari 2287"],
  ["WAKALAH","agency|representative|authorize|act|behalf|transaction|delegate","Qur’an 18:19"],
  ["SHUF‘AH","preemption|neighbor|co-owner|sale|share|property|priority","Sahih al-Bukhari 2257"],
  ["HIBAH","gift|voluntary|ownership|give|return|recipient|property","Sahih al-Bukhari 2589"],
  ["IMAN","faith|belief|heart|angels|books|messengers|Hereafter","Qur’an 2:285"],
  ["ISLAM","submission|Allah|religion|surrender|peace|obedience|Muslim","Qur’an 3:19"],
  ["KUFR","disbelief|reject|conceal|faith|ungrateful|truth|deny","Qur’an 2:6"],
  ["FISQ","disobedience|rebellion|sin|depart|obedience|wrongdoing|defiant","Qur’an 49:6"],
  ["AL-GHAYB","unseen|belief|hidden|Allah|future|angels|knowledge","Qur’an 2:3"],
  ["WAHY","revelation|Allah|prophet|message|inspiration|angel|scripture","Qur’an 42:51"],
  ["RISALAH","message|messenger|mission|deliver|Allah|people|guidance","Qur’an 7:62"],
  ["NUBUWWAH","prophethood|chosen|revelation|messenger|Allah|office|guidance","Qur’an 6:89"],
  ["MU‘JIZAH","miracle|prophet|sign|challenge|Allah|extraordinary|proof","Qur’an 17:59"],
  ["KARAMAH","saintly|gift|righteous|extraordinary|Allah|honor|event","Qur’an 3:37"],
  ["MALA’IKAH","angels|light|unseen|obey|Allah|messengers|wings","Qur’an 35:1"],
  ["JINN","unseen|fire|creatures|free will|Qur’an|humans|spirit","Qur’an 72:1"],
  ["BARZAKH","barrier|death|resurrection|intermediate|grave|return|world","Qur’an 23:100"],
  ["BA‘TH","resurrection|raised|dead|Day|life|graves|again","Qur’an 22:7"],
  ["HASHR","gathering|Day|people|resurrection|assemble|judgment|all","Qur’an 18:47"],
  ["MIZAN","scale|deeds|weigh|Judgment|balance|heavy|light","Qur’an 21:47"],
  ["SIRAT","bridge|Hell|cross|Hereafter|path|Judgment|passage","Sahih Muslim 183"],
  ["HAWD","basin|Prophet|water|Hereafter|drink|Day|followers","Sahih al-Bukhari 6579"],
  ["SHAFA‘AH","intercession|permission|Allah|Day|Prophet|plead|Judgment","Qur’an 2:255"],
  ["JANNAH","Paradise|gardens|rivers|reward|eternal|believers|Hereafter","Qur’an 3:15"],
  ["JAHANNAM","Hell|Fire|punishment|Hereafter|blaze|disbelief|destination","Qur’an 15:43"],
  ["AL-A‘RAF","heights|barrier|Paradise|Hell|people|recognize|wall","Qur’an 7:46"],
  ["SUHUF","scrolls|scriptures|Abraham|Moses|pages|revelation|earlier","Qur’an 87:18–19"],
  ["AL-LAWH AL-MAHFUZ","preserved|tablet|Qur’an|record|guarded|written|heavenly","Qur’an 85:21–22"],
  ["KURSI","seat|Allah|heavens|earth|knowledge|preservation|verse","Qur’an 2:255"],
  ["HIJRAH","migration|Mecca|Medina|leave|faith|journey|Prophet","Qur’an 9:40"],
  ["MUHAJIRUN","emigrants|Mecca|Medina|left|homes|faith|companions","Qur’an 59:8"],
  ["ANSAR","helpers|Medina|support|emigrants|companions|welcome|believers","Qur’an 59:9"],
  ["BAY‘AH","pledge|allegiance|hand|Prophet|commitment|believers|covenant","Qur’an 48:10"],
  ["AL-‘AQABAH","pledge|Medina|night|supporters|before|Hijrah|meeting","Sahih al-Bukhari 3893"],
  ["HUDAYBIYYAH","treaty|Mecca|peace|pilgrims|covenant|sixth|year","Qur’an 48:1"],
  ["ISRA’","night|journey|Mecca|Jerusalem|Prophet|Sacred|Mosque","Qur’an 17:1"],
  ["MI‘RAJ","ascension|heavens|night|Prophet|prayers|journey|above","Sahih al-Bukhari 3207"],
  ["GHAZWAH","campaign|Prophet|battle|expedition|participated|military|seerah","Sahih al-Bukhari 3949"],
  ["SARIYYAH","expedition|Prophet|did not|detachment|companions|mission|military","Sahih al-Bukhari 4260"],
  ["AHL AL-BAYT","household|Prophet|family|wives|kin|purification|respect","Qur’an 33:33"],
  ["SAHABAH","companions|Prophet|met|believed|generation|supporters|students","Qur’an 48:29"],
  ["TABI‘UN","successors|companions|generation|followed|students|early|believers","Qur’an 9:100"],
  ["KHALIFAH","successor|leader|earth|authority|steward|community|rule","Qur’an 2:30"],
  ["QADI","judge|court|dispute|ruling|evidence|justice|law","Qur’an 4:58"],
  ["MUFTI","jurist|fatwa|question|ruling|evidence|scholar|answer","Qur’an 4:127"],
  ["IJTIHAD","reasoning|jurist|evidence|effort|ruling|new|qualified","Sahih al-Bukhari 7352"],
  ["IJMA‘","consensus|scholars|agreement|community|ruling|generation|jurists","Qur’an 4:115"],
  ["QIYAS","analogy|legal|ruling|shared|cause|new|case","Qur’an 59:2"],
  ["MADHHAB","school|law|jurists|method|fiqh|rulings|tradition","Qur’an 16:43"],
  ["FATWA","legal|answer|question|scholar|ruling|nonbinding|evidence","Qur’an 4:127"],
  ["‘URF","custom|recognized|practice|society|law|reasonable|habit","Qur’an 7:199"],
  ["RUKHSAH","concession|ease|travel|illness|exception|ruling|hardship","Qur’an 2:185"],
  ["DARURAH","necessity|emergency|prohibited|survival|limit|exception|harm","Qur’an 2:173"],
  ["MAQASID AL-SHARIAH","objectives|law|welfare|faith|life|intellect|property","Qur’an 5:32; 16:90"]
];

cards.push(...v52WordRows.map(([prompt, clues, source], index) => ({
  type: 'say',
  prompt,
  answer: `Do not say: ${clues.split('|').join(' · ')}`,
  source,
  id: `WORD-${String(index + 101).padStart(3, '0')}`
})));
