/* v52 Decode rows: [sound-spelling, Arabic — meaning, usage label]. Native review remains required. */
const v52DecodeRows = [
  ["MA-KAN LAZIM-TAH KEE HAIK","ما كان لازم تحكي هيك — You should not have said that","Levantine Arabic"],
  ["KHAL LEE-NA NIF HAM-BAA DIL AWWAL","خلّينا نفهم بعض بالأول — Let us understand each other first","Levantine Arabic"],
  ["IL MAW DOO MISH MIS TAA HIL","الموضوع مش مستاهل — The issue is not worth all this","Levantine Arabic"],
  ["LA-THUT HAKEE-BIT TIM MEE","لا تحط كلام بتمّي — Do not put words in my mouth","Levantine Arabic"],
  ["DEER-BAA LAK A-HALAK","دير بالك ع حالك — Take care of yourself","Levantine Arabic"],
  ["MA-BID DEE KAB BIR-IL MAW DOO","ما بدي أكبر الموضوع — I do not want to make the issue bigger","Levantine Arabic"],
  ["IL HAKEE-SA HIL WIL FI IL AS AB","الحكي سهل والفعل أصعب — Talking is easy; acting is harder","Levantine Arabic"],
  ["KHOOD-WAK TAK WAF FAK KIR-MNEEH","خذ وقتك وفكّر منيح — Take your time and think carefully","Levantine Arabic"],
  ["ITHA-BID DAK IS SA RAA HA","إذا بدك الصراحة — If you want the honest answer","Levantine Arabic"],
  ["MA-AN DEE JA WAB-JA HIZ","ما عندي جواب جاهز — I do not have a ready answer","Levantine Arabic"],
  ["KILL-SHEE B-WAK TOH HIL W","كل شي بوقته حلو — Everything is better at its proper time","Levantine Arabic"],
  ["LA-TIS TAA JIL-BIL HUKUM","لا تستعجل بالحكم — Do not rush to judge","Levantine Arabic"],
  ["FAH HIM NEE-WIJ HIT NA THA RAK","فهّمني وجهة نظرك — Help me understand your point of view","Levantine Arabic"],
  ["KHAL LEE-NA NIR JAA-LIN NUK TA-LAS A SEE YEH","خلّينا نرجع للنقطة الأساسية — Let us return to the main point","Levantine Arabic"],
  ["MA-B SEE RIN KAM MIL-HAIK","ما بصير نكمّل هيك — We cannot keep going like this","Levantine Arabic"],
  ["SHOOD DA LEEL-A-HAL HAKEE","شو الدليل ع هالحكي؟ — What is the evidence for that claim?","Levantine Arabic"],
  ["YIM KIN-FIH MIT TAK GHA LAT","يمكن فهمتك غلط — Maybe I misunderstood you","Levantine Arabic"],
  ["MISH-KILL IKH TI LAAF-MISH KLEH","مش كل اختلاف مشكلة — Not every disagreement is a problem","Levantine Arabic"],
  ["IH KEE-MAA EE-B SA RAA HA","احكي معي بصراحة — Speak with me honestly","Levantine Arabic"],
  ["MA-BAW A DAK-B SHEE MA-BAK DAR-A LAY","ما بوعدك بشي ما بقدر عليه — I will not promise what I cannot do","Levantine Arabic"],
  ["MA-AN DEE-MA NAA BAS-WAD DIH LEE","ما عندي مانع، بس وضّحلي — I do not object; just clarify it for me","Levantine Arabic"],
  ["KHAL LEE-NA NIT TA FIK-MIN IL BI DAA YEH","خلّينا نتفق من البداية — Let us agree from the beginning","Levantine Arabic"],
  ["MEEN-KAAL IN NO-LA ZIM","مين قال إنّه لازم؟ — Who said it is required?","Levantine Arabic"],
  ["MA-BAK BAL-TAH KEE MAA EE-B HAL TA REE AH","ما بقبل تحكي معي بهالطريقة — I will not accept being spoken to that way","Levantine Arabic"],
  ["HAD-MISH WAK TIM NA SIB","هاد مش وقت مناسب — This is not an appropriate time","Levantine Arabic"],
  ["BID DEE-FAK KIR-KAB IL-MA JA WAB","بدي أفكّر قبل ما أجاوب — I need to think before I answer","Levantine Arabic"],
  ["LA-TAK TAA NEE-LOW SA MAHIT","لا تقاطعني لو سمحت — Please do not interrupt me","Levantine Arabic"],
  ["DAW WIR-AL HA KEE KA-KAB IL-MA TIN SHUR","دوّر على الحقيقة قبل ما تنشر — Look for the truth before you post","Levantine Arabic"],
  ["AA TA RIF-IN NAK-GHIL TIT","اعترف إنك غلطت — Admit that you were wrong","Levantine Arabic"],
  ["IL IH TI THAR-LA HA LO-MISH KI FA YEH","الاعتذار لحاله مش كفاية — An apology by itself is not enough","Levantine Arabic"],
  ["BID NA-HAL MISH-LAWM","بدنا حل، مش لوم — We need a solution, not blame","Levantine Arabic"],
  ["MA-BID DEE-AH KEE AN-HA DA-B GHEE YABO","ما بدي أحكي عن حدا بغيابه — I do not want to discuss someone behind their back","Levantine Arabic"],
  ["HAI-MISH KIS SIT EE-HAT TA-AH KEE HA","هاي مش قصتي حتى أحكيها — This is not my story to tell","Levantine Arabic"],
  ["LA-TIF HAM-SKOO TEE-MWA FA KA","لا تفهم سكوتي موافقة — Do not mistake my silence for agreement","Levantine Arabic"],
  ["IN NEE YEH-MNEE HA-BAS IN NA TEE JEH-MOO THI YEH","النيّة منيحة، بس النتيجة مؤذية — The intention is good, but the result is harmful","Levantine Arabic"],
  ["IL HU DOOD-MISH KIL LIT IH TI RAM","الحدود مش قلّة احترام — Boundaries are not disrespect","Levantine Arabic"],
  ["IL MSA A DEH-MA-LA ZIM-TKOON MIN NEH","المساعدة ما لازم تكون منّة — Help should not become leverage over someone","Levantine Arabic"],
  ["MA-KILL NA SEE HA-BTIN KAAL-KUD DAM-IN NAS","ما كل نصيحة بتنقال قدّام الناس — Not every piece of advice belongs in public","Levantine Arabic"],
  ["IL HAK-MA-B SEE R-MJA MA LEH","الحق ما بصير مجاملة — Truth should not become mere courtesy","Levantine Arabic"],
  ["KHAL LEE-NA NIS MAA-LIT TA RA FAIN","خلّينا نسمع للطرفين — Let us hear both sides","Levantine Arabic"],
  ["IL HA MAS-MISH BA DEEL-AN IL MAA RI FEH","الحماس مش بديل عن المعرفة — Enthusiasm is not a substitute for knowledge","Levantine Arabic"],
  ["MA-TAH KEE-B THI KEH-ITHA-MISH MIT AK KID","ما تحكي بثقة إذا مش متأكد — Do not speak confidently when you are unsure","Levantine Arabic"],
  ["IS AL-AH LIL KHIB REH","اسأل أهل الخبرة — Ask people with relevant expertise","Levantine Arabic"],
  ["IL KHA BAR-NA KIS-MIN DOON-SYA KO","الخبر ناقص من دون سياقه — A report is incomplete without its context","Levantine Arabic"],
  ["IS SOO RA-MISH KA MIL EH","الصورة مش كاملة — The picture is incomplete","Levantine Arabic"],
  ["MEEN-MAS DAR-IL MAA LOO MEH","مين مصدر المعلومة؟ — Who is the source of the information?","Levantine Arabic"],
  ["MOO-KILL MASH HOOR-KHA BEER","مو كل مشهور خبير — Not every famous person is an expert","Levantine Arabic"],
  ["LA-TIK HLAT-IR RAI-BIL HA KEE KA","لا تخلط الرأي بالحقيقة — Do not confuse opinion with fact","Levantine Arabic"],
  ["YIM KIN-FEE TAF SEER-TA NEE","يمكن في تفسير ثاني — There may be another explanation","Levantine Arabic"],
  ["MA-FEE-DAA EE-LIT TAJ REEH","ما في داعي للتجريح — There is no need for personal attacks","Levantine Arabic"],
  ["IN NAKD-MISH IH A NEH","النقد مش إهانة — Criticism is not an insult","Levantine Arabic"],
  ["IL KA RA MEH-A HAM-MIN IL FAWZ-BIN NI KASH","الكرامة أهم من الفوز بالنقاش — Dignity matters more than winning an argument","Levantine Arabic"],
  ["IS MAA-LIT FHAM-MISH LIT RUD","اسمع لتفهم، مش لترد — Listen to understand, not merely to reply","Levantine Arabic"],
  ["SHOO-IL LEE-GHAY YAR-RA YAK","شو اللي غيّر رأيك؟ — What changed your mind?","Levantine Arabic"],
  ["IL IH TI RAF-BAD MIL MAA RI FEH-KUW WEH","الاعتراف بعدم المعرفة قوّة — Admitting that you do not know is a strength","Levantine Arabic"],
  ["MA-BAA RIF-WAB DEE-IT AK KAD","ما بعرف وبدي أتأكد — I do not know, and I want to verify it","Levantine Arabic"],
  ["KHA LEEK-WA DIH-MIN DOON-MA TKOON-KA SEE","خليك واضح من دون ما تكون قاسي — Be clear without being harsh","Levantine Arabic"],
  ["IL LUTUF-MA-YAA NEE-ID DAAF","اللطف ما يعني الضعف — Gentleness does not mean weakness","Levantine Arabic"],
  ["IS SABUR-MA-YAA NEE-SKOO T-AN ID DULUM","الصبر ما يعني السكوت عن الظلم — Patience does not mean silence about injustice","Levantine Arabic"],
  ["IL MSA MA HA-MA-TIL GHEE-IL HU DOOD","المسامحة ما تلغي الحدود — Forgiveness does not erase boundaries","Levantine Arabic"],
  ["ITH THI KEH-BTIN BNA-SHWAI SHWAI","الثقة بتنبنى شوي شوي — Trust is built gradually","Levantine Arabic"],
  ["IL KHU SOO SEE YEH-HAK-MISH SIR REE YEH-MISH BOO HEH","الخصوصية حق، مش سرّية مشبوهة — Privacy is a right, not suspicious secrecy","Levantine Arabic"],
  ["LA-TIS TAKH DIM-ID DEEN-LIT RBAH-IN NI KASH","لا تستخدم الدين لتربح النقاش — Do not use religion merely to win an argument","Levantine Arabic"],
  ["ID DA LEEL-A HAM-MIN IS SAWT-IL AA LEE","الدليل أهم من الصوت العالي — Evidence matters more than a loud voice","Levantine Arabic"],
  ["KILL-WA HID-MAS OOL-AN KA LA MO","كل واحد مسؤول عن كلامه — Everyone is responsible for their words","Levantine Arabic"],
  ["IL KA LAM-ILO-AA WA KIB","الكلام إله عواقب — Words have consequences","Levantine Arabic"],
  ["MA-FEE-DAA EE-NOO SAL-LA HOON","ما في داعي نوصل لهون — We did not need to reach this point","Levantine Arabic"],
  ["BID DEE-MSA HA-MISH KHI SAM","بدي مساحة، مش خصام — I need space, not a fight","Levantine Arabic"],
  ["KHAL LEE-NA-NKAM MIL-LAM MA-NIH DA","خلّينا نكمّل لما نهدى — Let us continue when we are calmer","Levantine Arabic"],
  ["MA-BAK DAR-AK KAR-TAH TID DAGHT","ما بقدر أقرّر تحت الضغط — I cannot decide under pressure","Levantine Arabic"],
  ["IL KA RAR-IL AK-BIN NI HA YEH","القرار إلك بالنهاية — The decision is ultimately yours","Levantine Arabic"],
  ["A NA-BAH TA RIM-KA RA RAK-HAT TA-LAW IKH TA LAFT","أنا بحترم قرارك حتى لو اختلفت — I respect your decision even if I disagree","Levantine Arabic"],
  ["MA-BID DEE-BAR RIR-IL GHA LAT","ما بدي أبرّر الغلط — I do not want to excuse the wrong","Levantine Arabic"],
  ["ID DU ROOF-BIT FAS SIR-BAS-MA-BTAA FEE","الظروف بتفسّر، بس ما بتعفي — Circumstances explain, but do not erase responsibility","Levantine Arabic"],
  ["MA-TAH KUM-A-SH SHAKHIS-MIN MAW KIF-WA HID","ما تحكم ع الشخص من موقف واحد — Do not judge a person from one incident","Levantine Arabic"],
  ["IS AL-KAB IL-MA-TIF TA RID","اسأل قبل ما تفترض — Ask before you assume","Levantine Arabic"],
  ["IL WU DOOH-AR HAM-MIN IT TAL MEEH","الوضوح أرحم من التلميح — Clarity is kinder than hinting","Levantine Arabic"],
  ["MISH-KILL SKOOT-RI DA","مش كل سكوت رضا — Not every silence means approval","Levantine Arabic"],
  ["BAH HIB-AS MAA-RA YAK-B SA RAA HA","بحب أسمع رأيك بصراحة — I would like to hear your honest opinion","Levantine Arabic"],
  ["KHAL LEE-NA-NRA JAA-IL LEE-TA FAK NA-A LAY","خلّينا نراجع اللي اتفقنا عليه — Let us review what we agreed on","Levantine Arabic"],
  ["LA-TAN KUL-KHA BA RAN-KAB LA-AN TA TA HAK KAK-MIN HOO","لا تنقل خبراً قبل أن تتحقق منه — Do not relay a report before verifying it","Modern Standard Arabic"],
  ["IS SI YAK-YU GHA YIR-MAA NAL KA LAM","السياق يغيّر معنى الكلام — Context changes the meaning of speech","Modern Standard Arabic"],
  ["IL IH TI RAF-BIL KHA TA-BI DA YA TUL IS LAH","الاعتراف بالخطأ بداية الإصلاح — Admitting a mistake is the beginning of repair","Modern Standard Arabic"],
  ["LAI SA-KUL LOO-KHI LA FIN-KHU SOO MAH","ليس كل خلاف خصومة — Not every disagreement is hostility","Modern Standard Arabic"],
  ["UT LUB-ID DA LEEL-KAB LA-AN TUS DI RAL HUKM","اطلب الدليل قبل أن تصدر الحكم — Ask for evidence before reaching a judgment","Modern Standard Arabic"],
  ["LA-TAN SUB-EE LA-AH HAD-MAA LAM-YA KUL HOO","لا تنسب إلى أحد ما لم يقله — Do not attribute to anyone what they did not say","Modern Standard Arabic"],
  ["FAR RIK-BAI NAN NAS-WA TAF SEE RIK-LIN NAS","فرّق بين النص وتفسيرك للنص — Distinguish the text from your interpretation of it","Modern Standard Arabic"],
  ["HUS NUN NEE YEH-LA-YU SAH HIH-KUL LA-NA TEE JEH","حسن النية لا يصحح كل نتيجة — Good intentions do not correct every outcome","Modern Standard Arabic"],
  ["IH FAD-KA RA MA TA-MAN TAN SA HO","احفظ كرامة من تنصحه — Preserve the dignity of the person you advise","Modern Standard Arabic"],
  ["IN NA SEE HA-FIS SIR-AK RAB-IL AL IKH LAS","النصيحة في السر أقرب إلى الإخلاص — Private advice is closer to sincerity","Modern Standard Arabic"],
  ["LA-TAJ A LIL-GHA DAB-YA KOOD-KA RA RAK","لا تجعل الغضب يقود قرارك — Do not let anger drive your decision","Modern Standard Arabic"],
  ["IL ADL-AS AB-IN DA MA-YA TA AL LAK-BI MAN-TO HIB","العدل أصعب عندما يتعلق الأمر بمن تحب — Justice is harder when someone you love is involved","Modern Standard Arabic"],
  ["IS SKOOT-AN ID DULUM-LAI SA-HI YA DAN","السكوت عن الظلم ليس حياداً — Silence about injustice is not neutrality","Modern Standard Arabic"],
  ["AR RAH MAH-LA-TAA NEE-IL GHA-MAS OO LEE YEH","الرحمة لا تعني إلغاء المسؤولية — Mercy does not mean erasing responsibility","Modern Standard Arabic"],
  ["IL WA FA-BIL WAD-MAS OO LEE YEH","الوفاء بالوعد مسؤولية — Keeping a promise is a responsibility","Modern Standard Arabic"],
  ["LA-TA ID-BI MA-LA-TAS TA TEE-IL WA FA-BIH","لا تعد بما لا تستطيع الوفاء به — Do not promise what you cannot fulfill","Modern Standard Arabic"],
  ["IH TI RAM-IL KHU SOO SEE YEH-MIN HIF DIL A MA NEH","احترام الخصوصية من حفظ الأمانة — Respecting privacy is part of keeping a trust","Modern Standard Arabic"],
  ["LAI SAT-KUL LOO-MAA LOO MA TIN-SA HEE HA-SAA LI HA-LIN NASHR","ليست كل معلومة صحيحة صالحة للنشر — Not every true fact is appropriate to publish","Modern Standard Arabic"],
  ["IS AL-NAF SAK-MAN-SA YA TA DAR RAR","اسأل نفسك: من سيتضرر؟ — Ask yourself who may be harmed","Modern Standard Arabic"],
  ["IL IS LAH-YAH TAJ-EE LA-SID KIN-WA SABR","الإصلاح يحتاج إلى صدق وصبر — Repair requires honesty and patience","Modern Standard Arabic"],
  ["IL IH TI THAR-LA-YAK TA MIL-MIN DOON-TAGH YEER","الاعتذار لا يكتمل من دون تغيير — An apology is incomplete without change","Modern Standard Arabic"],
  ["LA-TAT LUB-IL MSA MA HA-LI TA TA JAN NAB-IL AA WA KIB","لا تطلب المسامحة لتتجنب العواقب — Do not seek forgiveness merely to avoid consequences","Modern Standard Arabic"],
  ["IS TA MAA-HAT TA-YAN TA HEE-LAA KHAR-MIN KA LA MIH","استمع حتى ينتهي الآخر من كلامه — Listen until the other person finishes speaking","Modern Standard Arabic"],
  ["IKH TAR-KA LI MA TAK-KAB LA-AN-TAR FAA-SAW TAK","اختر كلماتك قبل أن ترفع صوتك — Choose your words before raising your voice","Modern Standard Arabic"],
  ["KAD-YA KOON-RA YUK-SA EE BAN-WA TA REE KA TUK-MOO THI YEH","قد يكون رأيك صائباً وطريقتك مؤذية — Your opinion may be right while your method is harmful","Modern Standard Arabic"],
  ["MI NAL HIK MAH-AN TA KOOL-LA-A LAM","من الحكمة أن تقول: لا أعلم — It is wise to say that you do not know","Modern Standard Arabic"],
  ["TAGH YEER-IR RAI-BAA DA-THU HOOR-ID DA LEEL-A MA NEH","تغيير الرأي بعد ظهور الدليل أمانة — Changing your view after evidence appears is integrity","Modern Standard Arabic"],
  ["LA-TAJ A LISH SHUH RA-DA LEE LAN-A LAL ILM","لا تجعل الشهرة دليلاً على العلم — Do not treat fame as evidence of knowledge","Modern Standard Arabic"],
  ["IR JAA-EE LAL MAS DAR-IL AS LEE","ارجع إلى المصدر الأصلي — Return to the original source","Modern Standard Arabic"],
  ["LA-TAK TA TI-IL KA LAM-MIN SI YA KIH","لا تقتطع الكلام من سياقه — Do not remove words from their context","Modern Standard Arabic"],
  ["FAR RIK-BAI NAL AA DAH-WAL I BA DAH","فرّق بين العادة والعبادة — Distinguish custom from worship","Modern Standard Arabic"],
  ["LAI SA-KUL LOO-MA LOO FIN-WA JI BAN","ليس كل مألوف واجباً — Not everything familiar is obligatory","Modern Standard Arabic"],
  ["LA-TAJ A L-KHAW FAN NAS-YAH KUM-DA MEE RAK","لا تجعل الخوف من الناس يحكم ضميرك — Do not let fear of people rule your conscience","Modern Standard Arabic"],
  ["IN NEE YET-US SA LI HA-TAH TAJ-EE LA-A MA LIN-SA LIH","النية الصالحة تحتاج إلى عمل صالح — A sound intention needs sound action","Modern Standard Arabic"],
  ["HA SIB-NAF SAK-KAB LA-AN-TA LOOM-GHAI RAK","حاسب نفسك قبل أن تلوم غيرك — Examine yourself before blaming others","Modern Standard Arabic"],
  ["LA-TU BAR RIR-LI NAF SIK-MAA-TAR FU DOH-MI NAL AA KHA REEN","لا تبرر لنفسك ما ترفضه من الآخرين — Do not excuse in yourself what you reject in others","Modern Standard Arabic"],
  ["HU KOO KUN NAS-LA-TAS KUT-BI HUS NIL KASD","حقوق الناس لا تسقط بحسن القصد — Other people’s rights do not disappear because intentions were good","Modern Standard Arabic"],
  ["AT TAW BA-LA-TAA NEE-TA JA HUL-HU KOO KIL AA KHA REEN","التوبة لا تعني تجاهل حقوق الآخرين — Repentance does not mean ignoring others’ rights","Modern Standard Arabic"],
  ["AS SITR-LA-YAA NEE-TAM KEE NAL A THA","الستر لا يعني تمكين الأذى — Concealment does not mean enabling harm","Modern Standard Arabic"],
  ["IL HA THAR-LA-YU BAR RIR-SOO AD DUN-NID DA IM","الحذر لا يبرر سوء الظن الدائم — Caution does not justify permanent suspicion","Modern Standard Arabic"],
  ["IL HU DOOD-IL WA DI HA-TAH MEE-LI LA KAT","الحدود الواضحة تحمي العلاقات — Clear boundaries protect relationships","Modern Standard Arabic"],
  ["AT TA WA DU-LA-YAA NEE-IN KAR-IN NIA MAH","التواضع لا يعني إنكار النعمة — Humility does not mean denying a blessing","Modern Standard Arabic"],
  ["ASH SHUKR-YAD HAR-FEE HUS NIS TI MA LIN NIA MAH","الشكر يظهر في حسن استعمال النعمة — Gratitude appears in using a blessing well","Modern Standard Arabic"],
  ["AT TA WAK KUL-LA-YUL GHEE-IL AKH THA-BIL AS BAB","التوكل لا يلغي الأخذ بالأسباب — Reliance on Allah does not cancel responsible means","Modern Standard Arabic"],
  ["AR RI DA-LA-YAM NA-US SAA YA-EE LAL IS LAH","الرضا لا يمنع السعي إلى الإصلاح — Contentment does not prevent working toward repair","Modern Standard Arabic"],
  ["AS SABR-LAI SA-IS MAN-LIT TAS WEEF","الصبر ليس اسماً للتسويف — Patience is not another name for procrastination","Modern Standard Arabic"],
  ["IL ILM-IL LA THEE-LA-YU GHA YIR-IL A MAL-HUJ JA-TUN-A LA-SA HI BIH","العلم الذي لا يغيّر العمل حجة على صاحبه — Knowledge that does not change action testifies against its bearer","Modern Standard Arabic"],
  ["KATH RA TUL KA LAM-LA-TAA NEE-WU DOO HAL FIK RAH","كثرة الكلام لا تعني وضوح الفكرة — More words do not necessarily make an idea clearer","Modern Standard Arabic"],
  ["IJ AL-SU A LAK-AK RAB-EE LAL FAHM-MI NAL JI DAL","اجعل سؤالك أقرب إلى الفهم من الجدال — Let your question seek understanding more than argument","Modern Standard Arabic"],
  ["LA-TA TA HAD DATH-BIS MEE-MAN LAM-YU FAW WIDK","لا تتحدث باسم من لم يفوضك — Do not speak for someone who did not authorize you","Modern Standard Arabic"],
  ["IH THAR-AN-YUS BI HAL KHI LAF-BAH THAN-A NIL IN TI SAR","احذر أن يصبح الخلاف بحثاً عن الانتصار — Beware when disagreement becomes a search for victory","Modern Standard Arabic"],
  ["RA JI-AA THA RA-KA LA MIK-LA-NEE YA TAK-FA KAT","راجع أثر كلامك، لا نيتك فقط — Review the effect of your words, not only your intention","Modern Standard Arabic"],
  ["LA-TAS NAA-MIN KHA TA IN-WA HID-HU WEE YA-TUN KA MI LAH","لا تصنع من خطأ واحد هوية كاملة — Do not turn one mistake into someone’s entire identity","Modern Standard Arabic"],
  ["AA TIN NAS-FUR SA TAN-LI TAS HEEH-AKH TA IHIM","أعط الناس فرصة لتصحيح أخطائهم — Give people a chance to correct their mistakes","Modern Standard Arabic"],
  ["IL MSA WA-LA-TAA NEE-TA JA HUL-IKH TI LAF-IL HA JAT","المساواة لا تعني تجاهل اختلاف الحاجات — Equality does not mean ignoring different needs","Modern Standard Arabic"],
  ["IL IN SAF-YAB DA-IN DA MA-TAS MAA-MAA-LA-YU JI BUK","الإنصاف يبدأ عندما تسمع ما لا يعجبك — Fairness begins when you hear what you dislike","Modern Standard Arabic"],
  ["LA-TU AJ JIL-HAK KAN-LI AN NA-SA HI BA HOO-SA MIT","لا تؤجل حقاً لأن صاحبه صامت — Do not delay a right because its holder is silent","Modern Standard Arabic"],
  ["LA-TAJ A LIL-IH SAN-WA SEE LA TAN-LIS SAI TA RAH","لا تجعل الإحسان وسيلة للسيطرة — Do not turn generosity into a tool of control","Modern Standard Arabic"],
  ["IL WAKT-YAK SHIF-SID KAL IL TI ZAM","الوقت يكشف صدق الالتزام — Time reveals the truth of commitment","Modern Standard Arabic"],
  ["IB DA-BI MA-TAS TA TEE-IL IS TIM RAR-A LAYH","ابدأ بما تستطيع الاستمرار عليه — Begin with what you can sustain","Modern Standard Arabic"]
];

cards.push(...v52DecodeRows.map(([prompt, answer, source], index) => ({
  type: 'arabish', prompt, answer, source,
  id: `DECODE-${String(index + 161).padStart(3, '0')}`
})));
